import type { Product } from "@/types";

/**
 * Static product data
 * Images are stored in Cloudflare R2
 */
export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Handmade Rose Bouquet",
    slug: "handmade-rose-bouquet",
    description:
      "Beautiful handmade crocheted roses crafted with soft yarn in vibrant colors. Each petal is carefully shaped for a lifelike appearance. Perfect for everlasting decoration.",
    price: 29.99,
    regular_price: 29.99,
    on_sale: false,
    images: [
      {
        id: 1,
        src: "photo_1_2025-12-10_23-57-59.jpg",
        alt: "Handmade Rose Bouquet",
        name: "photo_1_2025-12-10_23-57-59.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Dreamy Blue Peony Vase",
    slug: "dreamy-blue-peony-vase",
    description:
      "Stunning crocheted blue and mint green peonies arranged in a beautiful white ceramic vase. This elegant arrangement features lush, full peonies with soft rope bow accents. Perfect for adding a sophisticated touch to any room with everlasting blooms.",
    price: 34.99,
    regular_price: 34.99,
    on_sale: false,
    images: [
      {
        id: 2,
        src: "photo_2_2025-12-10_23-57-59.jpg",
        alt: "Silk Peony Arrangement",
        name: "photo_2_2025-12-10_23-57-59.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: true,
    created_at: "2025-01-02T00:00:00Z",
    updated_at: "2025-01-02T00:00:00Z",
  },
  {
    id: 3,
    name: "Elegant Lily Stem",
    slug: "elegant-lily-stem",
    description:
      "Beautifully crocheted lily stems with intricate details. Made from premium yarn, each flower is carefully shaped to create an elegant everlasting bloom.",
    price: 24.99,
    regular_price: 24.99,
    on_sale: false,
    images: [
      {
        id: 3,
        src: "photo_3_2025-12-10_23-57-59.jpg",
        alt: "Elegant Lily Stem",
        name: "photo_3_2025-12-10_23-57-59.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: true,
    created_at: "2025-01-03T00:00:00Z",
    updated_at: "2025-01-03T00:00:00Z",
  },
  {
    id: 4,
    name: "Cherry Blossom Branch",
    slug: "cherry-blossom-branch",
    description:
      "Delicate crocheted cherry blossoms in soft pink tones. Each tiny bloom is handmade with fine yarn to capture the essence of spring year-round.",
    price: 27.99,
    regular_price: 27.99,
    on_sale: false,
    images: [
      {
        id: 4,
        src: "photo_2025-12-10_23-55-31.jpg",
        alt: "Cherry Blossom Branch",
        name: "photo_2025-12-10_23-55-31.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: true,
    created_at: "2025-01-04T00:00:00Z",
    updated_at: "2025-01-04T00:00:00Z",
  },
  {
    id: 5,
    name: "Lavender Bundle",
    slug: "lavender-bundle",
    description:
      "Charming crocheted lavender bundle in soothing purple hues. Each stem is carefully crafted with yarn to create a rustic, everlasting floral display.",
    price: 22.99,
    regular_price: 22.99,
    on_sale: false,
    images: [
      {
        id: 5,
        src: "photo_2025-12-10_23-57-14.jpg",
        alt: "Lavender Bundle",
        name: "photo_2025-12-10_23-57-14.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-05T00:00:00Z",
    updated_at: "2025-01-05T00:00:00Z",
  },
  {
    id: 6,
    name: "Orchid Spray",
    slug: "orchid-spray",
    description:
      "Luxurious crocheted orchid spray with intricate details. Each petal is meticulously shaped from premium yarn, creating an elegant centerpiece that lasts forever.",
    price: 39.99,
    regular_price: 39.99,
    on_sale: false,
    images: [
      {
        id: 6,
        src: "photo_2025-12-10_23-57-28.jpg",
        alt: "Orchid Spray",
        name: "photo_2025-12-10_23-57-28.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-06T00:00:00Z",
    updated_at: "2025-01-06T00:00:00Z",
  },
  {
    id: 7,
    name: "Tulip Collection",
    slug: "tulip-collection",
    description:
      "Vibrant crocheted tulips in cheerful colors. Each flower is handmade with soft yarn and wire stems, perfect for adding a pop of color to any room.",
    price: 31.99,
    regular_price: 31.99,
    on_sale: false,
    images: [
      {
        id: 7,
        src: "photo_2025-12-10_23-57-29.jpg",
        alt: "Tulip Collection",
        name: "photo_2025-12-10_23-57-29.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-07T00:00:00Z",
    updated_at: "2025-01-07T00:00:00Z",
  },
  {
    id: 8,
    name: "Hydrangea Bloom",
    slug: "hydrangea-bloom",
    description:
      "Full crocheted hydrangea blooms with clusters of tiny yarn flowers. Each piece is handcrafted to create a lush, textured arrangement that never fades.",
    price: 36.99,
    regular_price: 36.99,
    on_sale: false,
    images: [
      {
        id: 8,
        src: "photo_2025-12-10_23-57-30.jpg",
        alt: "Hydrangea Bloom",
        name: "photo_2025-12-10_23-57-30.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-08T00:00:00Z",
    updated_at: "2025-01-08T00:00:00Z",
  },
  {
    id: 9,
    name: "Daisy Chain",
    slug: "daisy-chain",
    description:
      "Cheerful crocheted daisies with white petals and yellow centers. Each flower is handmade with love, creating a playful and whimsical decoration.",
    price: 19.99,
    regular_price: 19.99,
    on_sale: false,
    images: [
      {
        id: 9,
        src: "photo_2025-12-10_23-57-31.jpg",
        alt: "Daisy Chain",
        name: "photo_2025-12-10_23-57-31.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-09T00:00:00Z",
    updated_at: "2025-01-09T00:00:00Z",
  },
  {
    id: 10,
    name: "Carnation Cluster",
    slug: "carnation-cluster",
    description:
      "Classic crocheted carnations with ruffled petals made from soft yarn. Each bloom is carefully crafted to capture the timeless beauty of traditional flowers.",
    price: 25.99,
    regular_price: 25.99,
    on_sale: false,
    images: [
      {
        id: 10,
        src: "photo_2025-12-10_23-57-32.jpg",
        alt: "Carnation Cluster",
        name: "photo_2025-12-10_23-57-32.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-01-10T00:00:00Z",
  },
  {
    id: 11,
    name: "Magnolia Blossom",
    slug: "magnolia-blossom",
    description:
      "Stunning crocheted magnolia blossoms with large, graceful petals. Each flower is handmade with premium yarn to create an elegant statement piece.",
    price: 33.99,
    regular_price: 33.99,
    on_sale: false,
    images: [
      {
        id: 11,
        src: "photo_2025-12-10_23-57-33.jpg",
        alt: "Magnolia Blossom",
        name: "photo_2025-12-10_23-57-33.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-11T00:00:00Z",
    updated_at: "2025-01-11T00:00:00Z",
  },
  {
    id: 12,
    name: "Sunflower Garden Bouquet",
    slug: "sunflower-garden-bouquet",
    description:
      "Bright and cheerful crocheted sunflowers in vibrant yellow with fluffy textured centers. Each flower is handmade with colorful yarn, bringing eternal sunshine to your space.",
    price: 28.99,
    regular_price: 28.99,
    on_sale: false,
    images: [
      {
        id: 12,
        src: "photo_3_2025-12-11_14-58-13.jpg",
        alt: "Sunflower Garden Bouquet",
        name: "photo_3_2025-12-11_14-58-13.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: true,
    created_at: "2025-01-12T00:00:00Z",
    updated_at: "2025-01-12T00:00:00Z",
  },
  {
    id: 13,
    name: "Jellyfish Dreams Hanging",
    slug: "jellyfish-dreams-hanging",
    description:
      "Whimsical crocheted hanging decoration resembling a jellyfish or pom pom mobile. Features a colorful domed top with pink, purple, and cream stripes, with long flowing pink tendrils cascading down. Perfect artistic statement piece for bedrooms, nurseries, or any creative space.",
    price: 26.99,
    regular_price: 26.99,
    on_sale: false,
    images: [
      {
        id: 13,
        src: "photo_4_2025-12-11_14-58-13.jpg",
        alt: "Poppy Field",
        name: "photo_4_2025-12-11_14-58-13.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-13T00:00:00Z",
    updated_at: "2025-01-13T00:00:00Z",
  },
  {
    id: 14,
    name: "Golden Sunshine Potted Bloom",
    slug: "golden-sunshine-potted-bloom",
    description:
      "Cheerful crocheted sunflower in a cute cream-colored pot. Features bright yellow petals arranged in a full, sunny bloom with a detailed brown spiral center and green stem. Perfect desktop companion or shelf decoration that brings joy year-round.",
    price: 37.99,
    regular_price: 37.99,
    on_sale: false,
    images: [
      {
        id: 14,
        src: "photo_5_2025-12-11_14-58-13.jpg",
        alt: "Camellia Beauty",
        name: "photo_5_2025-12-11_14-58-13.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-14T00:00:00Z",
    updated_at: "2025-01-14T00:00:00Z",
  },
  {
    id: 15,
    name: "Purple Orchid & Daisy Elegance",
    slug: "purple-orchid-daisy-elegance",
    description:
      "Beautiful mixed bouquet featuring a large lavender orchid with pointed petals and cheerful white daisies with bright yellow centers. Wrapped in vintage newspaper with elegant gold ribbon accents and white organza bow. A sophisticated and charming arrangement with classic appeal.",
    price: 32.99,
    regular_price: 32.99,
    on_sale: false,
    images: [
      {
        id: 15,
        src: "photo_6_2025-12-11_14-58-13.jpg",
        alt: "Iris Display",
        name: "photo_6_2025-12-11_14-58-13.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-15T00:00:00Z",
    updated_at: "2025-01-15T00:00:00Z",
  },
  {
    id: 16,
    name: "Romantic Lilac Bunch",
    slug: "romantic-lilac-bunch",
    description:
      "Charming crocheted lilac bouquet with four tall stems featuring densely packed flower clusters in complementary colors: light lavender, deep purple, dark plum, and soft pink. Wrapped in cream paper with a beautiful purple ribbon bow. Elegant and sophisticated arrangement perfect for special occasions.",
    price: 30.99,
    regular_price: 30.99,
    on_sale: false,
    images: [
      {
        id: 16,
        src: "photo_7_2025-12-11_14-58-13.jpg",
        alt: "Purple Lavender Bouquet",
        name: "photo_7_2025-12-11_14-58-13.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-16T00:00:00Z",
    updated_at: "2025-01-16T00:00:00Z",
  },
  {
    id: 17,
    name: "Love & Flowers Deluxe Gift Set",
    slug: "love-flowers-deluxe-gift-set",
    description:
      "Stunning gift set featuring two beautiful arrangements: a simple elegant bouquet with a red rose and white baby's breath, plus a deluxe decorative gift box bursting with bright orange daisies, pink ruffled peonies, white accents, blue heart decoration, and green foliage. Perfect romantic gift with 'My Heart is with You' sentiment. Includes both pieces wrapped with red ribbon bows.",
    price: 29.99,
    regular_price: 29.99,
    on_sale: false,
    images: [
      {
        id: 17,
        src: "photo_8_2025-12-11_14-58-13.jpg",
        alt: "Orange Gerbera Mix",
        name: "photo_8_2025-12-11_14-58-13.jpg",
      },
    ],
    categories: [],
    stock_status: "instock",
    featured: false,
    created_at: "2025-01-17T00:00:00Z",
    updated_at: "2025-01-17T00:00:00Z",
  },
];
